# Generated by Django 5.2 on 2025-04-11 13:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="venueevent",
            name="status",
            field=models.CharField(
                choices=[("open", "open"), ("closed", "closed")],
                default="open",
                verbose_name="Статус мероприятия",
            ),
        ),
    ]
